Repository michaelwp/logic-practice, pull requests merged in 2022-10, with the labels that each got.

#1 matrix spiral step
  README.md
  golang/matrix.go
  golang/matrix_test.go
Labels: enhancement, hacktoberfest-accepted

#4 fix matrix spiral step, handle parameter value
  golang/matrix.go
  golang/matrix_test.go
Labels: hacktoberfest-accepted, hotfix

#5 Implements the palindrome algorithm in typescript
  .gitignore
  typescript/package.json
  typescript/src/palindrome.ts
  typescript/tests/palindrome.test.ts
  typescript/tsconfig.json
  typescript/tsconfig.spec.json
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#8 is anagram
  golang/anagram.go
  golang/anagram_test.go
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#9 fix letter case bug
  README.md
  golang/anagram.go
  golang/anagram_test.go
Labels: bug, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, improvement

#10 Implemented flip-flop in typescript
  typescript/package.json
  typescript/src/flip-flop.ts
  typescript/tests/flip-flop.test.ts
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#11 array is sub sequence
  README.md
  golang/array_is_sub_sequence.go
  golang/array_is_sub_sequence_test.go
  golang/array_number_of_pair_sum_x.go
  golang/array_number_of_pair_sum_x_test.go
  golang/array_peak_element.go
  golang/array_peak_element_test.go
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#12 linked list shift node position
  README.md
  golang/linked_list.go
  golang/linked_list_test.go
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#14 reverse node
  README.md
  golang/linked_list.go
  golang/linked_list_test.go
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#15 sherolock & anagram
  README.md
  golang/anagram.go
  golang/anagram_test.go
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#16 the nearest block
  README.md
  golang/the_nearest_block.go
  golang/the_nearest_block_test.go
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022
